In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
import pickle

In [2]:
data = pd.read_csv("../data/Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
data = data.drop(['RowNumber','CustomerId','Surname'], axis=1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
## Encode categorical variable
lable_encoder_gender = LabelEncoder()
data['Gender'] = lable_encoder_gender.fit_transform(data['Gender'])

In [6]:
## Onehot encode 'Geography'
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder(handle_unknown='ignore')
geo_encoder = onehot_encoder.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoder,columns=onehot_encoder.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
### Combine one hot encoder columns with the orignal data
data = pd.concat([data.drop(['Geography'],axis=1),geo_encoded_df],axis=1)

In [8]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [9]:
X = data.drop('EstimatedSalary',axis=1)

In [10]:
y = data['EstimatedSalary']

In [11]:
## Split the data in training adn testing sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state=42)

In [12]:
### Scale these features
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [13]:
### Save the encoder and scalar
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(lable_encoder_gender,file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder,file)

with open("scalar.pkl",'wb') as file:
    pickle.dump(scalar, file)

#### ANN Regression Problem

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [15]:
### Build our ANN
model = Sequential([
    Dense(64, activation="relu", input_shape =(X_train.shape[1],)),    ### HL1 connected with input layer
    Dense(32, activation="relu"),   ### HL2
    Dense(1)   ### output Layer for linear regression
])

### Compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

d:\AIML Projects\Customer Churn Prediction ANN\venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
### Set up the Tensorboard
log_dir = "regression/logs/fits/" +datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [19]:
### Setup early stopping
earaly_stopping_callback = EarlyStopping(monitor='val_loss', patience=10,restore_best_weights=True)

In [20]:
### Train the model
history = model.fit(
    X_train,y_train,validation_data=(X_test,y_test), epochs = 100,
    callbacks = [tensorflow_callback,earaly_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 100370.1484 - mae: 100370.1484 - val_loss: 98491.8516 - val_mae: 98491.8516
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 99523.9219 - mae: 99523.9219 - val_loss: 96771.3047 - val_mae: 96771.3047
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 96514.8125 - mae: 96514.8125 - val_loss: 92368.7188 - val_mae: 92368.7188
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 90619.6484 - mae: 90619.6484 - val_loss: 85098.0312 - val_mae: 85098.0312
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 82159.8516 - mae: 82159.8516 - val_loss: 75959.8516 - val_mae: 75959.8516
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 72543.4922 - mae: 72543.4922 - val_loss: 66887.4922 - val_mae: 66887.4922
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 63693.8594 - mae: 63693.8594 - val_loss: 59354.9961 - val_mae: 59354.9961
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 57091.9492 - mae: 57091.9492 - val_loss: 54484.4648 - val_mae: 54484.4648
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 53177.7773 - mae: 53177.7773 - val_loss: 51996.1172 - val_mae: 51996.1172
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51311.3672 - mae: 51311.3672 - val_loss: 51167.1680 - val_mae: 51167.1680
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50628.8398 - mae: 50628.8398 - val_loss: 50939.7891 - val_mae: 50939.7891
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50396.3867 - mae: 50396.3867 - val_loss: 50848.9492 - val_mae: 50848.9492
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50281.2734 - mae: 50281.2734 - val_loss: 50791.0938 - val_mae: 50791.0938
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50209.6484 - mae: 50209.6484 - val_loss: 50747.2461 - val_mae: 50747.2461
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50151.2539 - mae: 50151.2539 - val_loss: 50714.2695 - val_mae: 50714.2695
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50098.8477 - mae: 50098.8477 - val_loss: 50668.3359 - val_mae: 50668.3359
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50055.1992 - mae: 50055.1992 - val_loss: 50636.3164 - val_mae: 50636.3164
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50012.9102 - mae: 50012.9102 - val_loss: 50596.8477 - val_mae: 50596.8477
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49976.7578 - mae: 49976.7578 - val_loss: 50571.1016 - val_mae: 50571.1016
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49941.8789 - mae: 49941.8789 - val_loss: 50558.9141 - val_mae: 50558.9141
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49914.4141 - mae: 49914.4141 - val_loss: 50526.7695 - val_mae: 50526.7695
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49887.8438 - mae: 49887.8438 - val_loss: 50508.0859 - val_mae: 50508.0859
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49856.1719 - mae: 49856.1719 - val_loss: 50497.2148 - val_mae: 50497.2148
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49833.1992 - mae: 49833.1992 - val_loss: 50483.5781 - val_mae: 50483.5781
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49813.5117 - mae: 49813.5117 - val_loss: 50467.6836 - val_mae: 50467.6836
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49790.1211 - mae: 49790.1211 - val_loss: 50455.0508 - val_mae: 50455.0508
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49768.3711 - mae: 49768.3711 - val_loss: 50445.8203 - val_mae: 50445.8203
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49751.3672 - mae: 49751.3672 - val_loss: 50424.8516 - val_mae: 50424.8516
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49731.4570 - mae: 49731.4570 - val_loss: 50422.3945 - val_mae: 50422.3945
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49716.5078 - mae: 49716.5078 - val_loss: 50413.2227 - val_mae: 50413.2227
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49699.9492 - mae: 49699.9492 - val_loss: 50405.6172 - val_mae: 50405.6172
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49685.4414 - mae: 49685.4414 - val_loss: 50408.7656 - val_mae: 50408.7656
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49670.2188 - mae: 49670.2188 - val_loss: 50396.3789 - val_mae: 50396.3789
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49657.9922 - mae: 49657.9922 - val_loss: 50389.7578 - val_mae: 50389.7578
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49646.7109 - mae: 49646.7109 - val_loss: 50382.5234 - val_mae: 50382.5234
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49633.2852 - mae: 49633.2852 - val_loss: 50383.8203 - val_mae: 50383.8203
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49623.4766 - mae: 49623.4766 - val_loss: 50370.0273 - val_mae: 50370.0273
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49610.0859 - mae: 49610.0859 - val_loss: 50360.9844 - val_mae: 50360.9844
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49598.1875 - mae: 49598.1875 - val_loss: 50353.1016 - val_mae: 50353.1016
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49590.5625 - mae: 49590.5625 - val_loss: 50351.7695 - val_mae: 50351.7695
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49579.1953 - mae: 49579.1953 - val_loss: 50350.2578 - val_mae: 50350.2578
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49571.3711 - mae: 49571.3711 - val_loss: 50349.8789 - val_mae: 50349.8789
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49559.3555 - mae: 49559.3555 - val_loss: 50347.1680 - val_mae: 50347.1680
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49553.1406 - mae: 49553.1406 - val_loss: 50347.0039 - val_mae: 50347.0039
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49541.9102 - mae: 49541.9102 - val_loss: 50327.2383 - val_mae: 50327.2383
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49535.4883 - mae: 49535.4883 - val_loss: 50331.1016 - val_mae: 50331.1016
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49527.4375 - mae: 49527.4375 - val_loss: 50332.4453 - val_mae: 50332.4453
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49517.7422 - mae: 49517.7422 - val_loss: 50335.4492 - val_mae: 50335.4492
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49510.9453 - mae: 49510.9453 - val_loss: 50332.6602 - val_mae: 50332.6602
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49504.4844 - mae: 49504.4844 - val_loss: 50329.2734 - val_mae: 50329.2734
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49497.2734 - mae: 49497.2734 - val_loss: 50341.7812 - val_mae: 50341.7812
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49492.0742 - mae: 49492.0742 - val_loss: 50329.0781 - val_mae: 50329.0781
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49485.4219 - mae: 49485.4219 - val_loss: 50327.3594 - val_mae: 50327.3594
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49478.4570 - mae: 49478.4570 - val_loss: 50323.1133 - val_mae: 50323.1133
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49471.6797 - mae: 49471.6797 - val_loss: 50329.3828 - val_mae: 50329.3828
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49466.7930 - mae: 49466.7930 - val_loss: 50341.0547 - val_mae: 50341.0547
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49466.0781 - mae: 49466.0781 - val_loss: 50331.0117 - val_mae: 50331.0117
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49457.9961 - mae: 49457.9961 - val_loss: 50338.2617 - val_mae: 50338.2617
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49452.8164 - mae: 49452.8164 - val_loss: 50332.3281 - val_mae: 50332.3281
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49445.2344 - mae: 49445.2344 - val_loss: 50332.9883 - val_mae: 50332.9883
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49440.7852 - mae: 49440.7852 - val_loss: 50337.1055 - val_mae: 50337.1055
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49432.5977 - mae: 49432.5977 - val_loss: 50338.7031 - val_mae: 50338.7031
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49428.6562 - mae: 49428.6562 - val_loss: 50353.4102 - val_mae: 50353.4102
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49424.4297 - mae: 49424.4297 - val_loss: 50345.5352 - val_mae: 50345.5352

In [21]:
### Load Tensorboard Extension
%load_ext tensorboard

In [23]:
%tensorboard --logdir regression/logs/fits

Reusing TensorBoard on port 6006 (pid 18284), started 0:00:09 ago. (Use '!kill 18284' to kill it.)

In [24]:
### Evaluate model on the test data
test_loss,test_mae = model.evaluate(X_test,y_test)
print(f'Test MAE {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50323.1133 - mae: 50323.1133
Test MAE 50323.11328125

In [26]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.